API_KEY: insert_yours
API_SECRET: insert_yours

blacklisted_symbols:
  - BCCUSDT
  - BCHABCUSDT
  - BCHSVUSDT
  - BUSDUSDT
  - EURUSDT
  - PAXGUSDT
  - PAXUSDT
  - SUSDUSDT
  - TUSDUSDT
  - USDCUSDT
  - USDPUSDT
  - USDSBUSDT
  - USDSUSDT
